[package]
authors = ["FL03 <jo3mccain@icloud.com> (https://github.com/FL03)"]
categories = []
description = "template-cli-rs"
edition = "2021"
homepage = "https://github.com/FL03/template-cli-rs/wiki"
keywords = ["app", "binary", "clap", "cli", "template"]
license = "Apache-2.0"
name = "template-cli-rs"
readme = "README.md"
repository = "https://github.com/FL03/template-cli-rs"
version = "0.1.0"

[[bin]]
bench = true
name = "cli"
path = "src/main.rs"
test = true

[build-dependencies]

[dependencies]
clap = { features = ["cargo", "derive", "env"], version = "4.0.29" }
futures = "0.3.25"
scsys = { features = ["full"], version = "0.1.36" }
serde = { features = ["derive"], version = "1.0.149" }
serde_json = "1.0.89"
strum = { features = ["derive"], version = "0.24.1" }
tokio = { features = ["full"], version = "1.22.0" }
tracing = "0.1.36"
tracing-subscriber = { features = ["env-filter"], version = "0.3.15" }

[dev-dependencies]

[profile.dev]
codegen-units = 256
debug = true
debug-assertions = true
incremental = true
lto = false
panic = 'unwind'
rpath = false
opt-level = 0
overflow-checks = true

[profile.release]
codegen-units = 16
debug = false
debug-assertions = false
incremental = false
lto = false
panic = 'unwind'
rpath = false
opt-level = 'z'
overflow-checks = false
